### ISSUE TITLE
Error page realignment

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#1]
![newcon-06-error](https://user-images.githubusercontent.com/41282864/43766951-1eb71db8-9a34-11e8-91ec-5b4e2252f3a5.png)
Need to realign Error page.
See attached picture.

Next steps...

- Adding suggestion about what to do next (nt only dashboard)
- Offering courses
- Going back to previous position (if possible

**Comment by svarlamov** [comment]
We only have text (and image) for the 404 (not found) page... I think another task is to create them for 403 (forbidden), 400 (bad request), 5XXs (server errors) @LanderMuruaga

**Comment by LanderMuruaga** [comment]
Different error pages:
Note they all have same image, but will be nice to add a slightly different one for each.
- The **message** is different in all of them. The image needs to be adapted to each content adding contextual elements adapted to the message itself.
- The **objective** is to help users realize the message is different.

Image suggestions for each page/Sage...

- [ ]  404 - Question marks floating around Sage.
![400-badrequest](https://user-images.githubusercontent.com/41282864/44099335-b077a610-9fe2-11e8-982b-3c9de9436fdb.png)

- [ ]  403 - Lock & keys floating around Sage
![403-error](https://user-images.githubusercontent.com/41282864/44099337-b0a1733c-9fe2-11e8-8b95-e5e41c502833.png)

- [ ]  400 - Strange simbols like #@?! floating around Sage (like insults in comics)
![404-error](https://user-images.githubusercontent.com/41282864/44099338-b0c8d45e-9fe2-11e8-9a56-244198f20d23.png)

- [ ]  500 - Little servers floating around Sage (???)
![500-servererror](https://user-images.githubusercontent.com/41282864/44099339-b0f41984-9fe2-11e8-93ff-0c26345087ae.png)

**Comment by LanderMuruaga** [comment]
Here are the different Sages, customized for each error page... 
![error_400](https://user-images.githubusercontent.com/41282864/44509126-04844680-a6b1-11e8-9515-9b6aa01d78e6.png)
![error_403](https://user-images.githubusercontent.com/41282864/44509127-051cdd00-a6b1-11e8-9a48-0062d7f3fe70.png)
![error_404](https://user-images.githubusercontent.com/41282864/44509129-051cdd00-a6b1-11e8-9cc1-774f4e14d780.png)
![error_500](https://user-images.githubusercontent.com/41282864/44509130-051cdd00-a6b1-11e8-89a8-98dbccdee154.png)

**Comment by svarlamov** [comment]
@andyluu1908 Can you wrap up this issue when you have a chance? Think all that's left is settting up the images. LMK if you need help and I can upload them to S3

**Comment by andyluu1908** [comment]
@svarlamov please upload them into S3 and give me the links.

**Comment by svarlamov** [comment]
https://s3-us-west-2.amazonaws.com/exlskills-error-images/sage-expl.png
https://s3-us-west-2.amazonaws.com/exlskills-error-images/sage-keys.png
https://s3-us-west-2.amazonaws.com/exlskills-error-images/sage-question.png
https://s3-us-west-2.amazonaws.com/exlskills-error-images/sage-meh.png

**Comment by svarlamov** [comment]
@andyluu1908

**Comment by svarlamov** [comment]
Done via https://github.com/exlskills/web-client/pull/5
