### ISSUE TITLE
Introductory Overlay Screen Minimization

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#10]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** When you click on "Write a reply" to insert a cursor the message minimizes to the bottom right and the cursor appears in the text input area there.

**How to Recreate:** Click on "Write a reply" when looking at the introductory message for the course.

**What to Fix:** The transition between the two is very awkward.

**Expected Outcome:** Allow the user to enter their response back in the text area provided on the overlay and once "enter" is pressed /a "send" icon? and the message sends then it should be minimized.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/43923983-555bf8b6-9bf1-11e8-8704-c67a7affa509.png)

**Comment by svarlamov** [comment]
Agree. Since I'm seeing a lot of intercom-related issues here, I'll give you access and you can talk to their support/customize these things to the extent that they are customizable.

**Comment by svarlamov** [comment]
Invite sent @kkhenkina-EXL

**Comment by svarlamov** [comment]
CC @LanderMuruaga - I think that this is more related to what you have been/are working on re:intercom. Please close if you think that this is covered elsewhere.

**Comment by svarlamov** [comment]
@kkhenkina-EXL @LanderMuruaga I don't think that there's anything that we can currently do about this... Depending on the outcome of your conversations with the Intercom folks, I recommend to close this issue

**Comment by LanderMuruaga** [comment]
Agree, I think is better to close by now, and  we can address it later.
