### ISSUE TITLE
Sage 

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#11]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** Sage does not understand questions about how to navigate the site.

**How to Recreate:** Ask a question about how to access a course or register.

**What to Fix:** The responses that Sage provides.

**Expected Outcome:** I would expect "How do I access a course" to provide instructions on how to do so, same with registration. Like "1. Click on "Login/Sign-up" in top right corner. 2. Complete all necessary information." etc.

**Current State Screenshot:** ![image](https://user-images.githubusercontent.com/33239272/43924363-730bcae8-9bf2-11e8-93ba-88508a7e5692.png)

**Comment by svarlamov** [comment]
CC @LanderMuruaga I think this should be a task for this week on the product side, to create a list for this. Please DM me

**Comment by svarlamov** [comment]
Issue old/deprecated by move to spf-server
