### ISSUE TITLE
Day/Night Theme Switcher

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#12]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** When the theme is changed from light/dark the chat stays the same color.

**How to Recreate:** Click on the switching button in the top right corner.

**What to Fix:** The chat box.

**Expected Outcome:** Should switch color themes with the rest of the page.

**Current State Screenshot:** ![image](https://user-images.githubusercontent.com/33239272/43924914-cc46d3ae-9bf3-11e8-8dd1-77eb644cbf55.png)

**Comment by svarlamov** [comment]
The chat -- at least for the time being -- is provided by Intercom, and we actually can't change the GUI color dynamically
