### ISSUE TITLE
Dashboard Component Misalignment 

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#13]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** The components within the frames on the dashboard page are misaligned.

**How to Recreate:** Navigate to the Dashboard.

**What to Fix:** The "View All..." and the table in the learning activity section

**Expected Outcome:** The "View All..." should be left-aligned to the scroll button above. Same with the table edge in the "My Learning Activity" component.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/43925132-75b31d4e-9bf4-11e8-9caf-2b14d46358f3.png)

**Comment by svarlamov** [comment]
Sorry but this isn't a bug... CC @LanderMuruaga if you have comments

**Comment by svarlamov** [comment]
@LanderMuruaga Pls comment on this

**Comment by LanderMuruaga** [comment]
Right is not a bug. Also, I'll keep it in a second layer as we'll need to update the backend sooner or later and we have a clear idea about this kind of tasks.

**Comment by svarlamov** [comment]
Issue deprecated by move to spf-server
