### ISSUE TITLE
Notifications Presentation

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#14]
**URL:** https://exlskills.com/learn-en/notifications

**Current behavior:** The Notifications page content is misaligned.

**How to Recreate:** Navigate to the Notifications page https://exlskills.com/learn-en/notifications while not logged in and have no notifications.

**What to Fix:** Alignment of page content.

**Expected Outcome:** The "Notifications" header and the "You don't have any notifications to display here yet" should be left-aligned in the content pane.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/43925374-17ff2926-9bf5-11e8-95ab-adbfa0871c9f.png)

**Comment by svarlamov** [comment]
CC @LanderMuruaga

**Comment by LanderMuruaga** [comment]
Different type of notifications. 
Not sure if we can go that way on right sidebar or if it's useful.
![newcon-09-notofications](https://user-images.githubusercontent.com/41282864/44088907-20c2f802-9fc5-11e8-837d-cd1434a21634.png)

**Comment by LanderMuruaga** [comment]
Current style notifications; No content + Notifications.

![nonotifications](https://user-images.githubusercontent.com/41282864/44194572-b1514780-a136-11e8-9deb-dc3993d18ce4.png)

We can use badges or not. It could be nice for a future to easily understand where are the notifications coming from.
![notifications](https://user-images.githubusercontent.com/41282864/44194594-bb734600-a136-11e8-8b94-d76b0f769dfc.png)

**Comment by svarlamov** [comment]
Issue deprecated by move to spf-server
