### ISSUE TITLE
Notifications Access

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#15]
**URL:** https://exlskills.com/learn-en/notifications

**Current behavior:** As a not logged in user of the service I still see the notifications icon and have access to a "My Notifications" page.

**How to Recreate:** Click on the notification icon and then "See all notifications"

**What to Fix:** The icon and the page itself should not be accessible without an account.

**Expected Outcome:** The icon should be removed and the page should be blocked to access without a login.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/43925691-f5bcab94-9bf5-11e8-9ecf-c691a8b7350e.png)

**Comment by svarlamov** [comment]
I don't see the point of blocking that page without an account... People should be able to do just about anything, except for things that (a) have the potential to users of the spam the platform unless users are verified; or (b) require authentication for processing of data, without having to be logged in.

If you use the same device, you'll find that things will work pretty seamlessly between sessions. I also imagine that we will sooner or later use the notifications box to push engagement notifications that users -- logged in or not -- should see.

**Comment by svarlamov** [comment]
CC @LanderMuruaga I guess, but I would like to close

**Comment by svarlamov** [comment]
@LanderMuruaga Pls check and close

**Comment by LanderMuruaga** [comment]
To me makes sense what Sasha is saying. Actually both, but personally I see the Notifications like they way the system is communicating with the user and where users can track and check everything the system is telling them. 
i.e. If you are NOT logged in and you finish a unit, the system should tell you something or should react with a little notification (like... Hey, nice job!), and to me this is the place to see all of them. 
In case you are logged, you'll also be able to check historical data about your notifications and maybe more targeted with suggestions, etc.
