### ISSUE TITLE
Inappropriate Cursor Changes

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#16]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** Even when there is nothing to scroll the cursor still changes to a clicker when hovering over the buttons.

**How to Recreate:** Hover over the left/right navigation buttons on the course carousel.

**What to Fix:** The cursor's behaviour during hover-over.

**Expected Outcome:** The cursor shouldn't change if there is nothing to click - when there aren't enough courses for the carousel to work.

**Current State Screenshot:** ![image](https://user-images.githubusercontent.com/33239272/43925874-901b62d4-9bf6-11e8-943e-53e43a956e5f.png)

**Comment by svarlamov** [comment]
I'm about 90% sure that this is handled by some sort of carousel lib... Hopefully, it's customizable. Will leave this to community for now

**Comment by svarlamov** [comment]
Issue deprecated by move to spf-server
