### ISSUE TITLE
Course badges by topic

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#2]
Currently the course badge is hard-coded to always be the Java logo, but it should be dynamic based on the course's primary topic. For now it's okay to store the map of primary topic to badge on the client...

- [x] @LanderMuruaga Create/pull down course badges for Python, Go, C, C++, HTML, CSS, JS, TypeScript, Java (we already have but you can provide updated if you think we should improve it), UI Design, UX Design, UI/UX, DevOps, SQL, R, C#, .NET, Bash/Shell, PHP, Ruby, Swift, Kotlin, Scala, and one more as a default for unknown topics

- [x] Create map of primary topic key to image URL in web-client

- [x] Add to course card (per Lander's previous designs)

- [x] (ref A in scrn cap) Use the new topic to image map on the course page (remove the hard-coded java default)

![image](https://user-images.githubusercontent.com/10859025/43836175-180b5538-9b47-11e8-97fb-c793299f1d83.png)

**Comment by LanderMuruaga** [comment]
Course category icons
![category-icons2](https://user-images.githubusercontent.com/41282864/44084760-e44cebec-9fb7-11e8-80e9-c9dd91cf9c7f.png)
[Category-Icons.zip](https://github.com/exlskills/exlskills/files/2286376/Category-Icons.zip)

**Comment by svarlamov** [comment]
Hosted at root path: https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/

File names (slightly renamed):

```
bash-shell.png
c-plus-plus.png
c-sharp.png
c.png
css.png
dev-ops.png
dotnet.png
go.png
html.png
java.png
javascript.png
kotlin.png
php.png
python.png
r.png
ruby.png
scala.png
sql.png
swift.png
typescript.png
ui-design.png
ux-design.png
```

**Comment by svarlamov** [comment]
@LanderMuruaga Can you also attach a default/unknown badge? Thanks

**Comment by LanderMuruaga** [comment]
Added the default icon (default-exl.png) + renamed all icons.
[Category-Icons.zip](https://github.com/exlskills/exlskills/files/2292909/Category-Icons.zip)
![category-icons](https://user-images.githubusercontent.com/41282864/44196958-ab129980-a13d-11e8-8703-a31790c38fba.png)

**Comment by svarlamov** [comment]
Did you mean to close this?

**Comment by LanderMuruaga** [comment]
Not really. My fault :)

**Comment by svarlamov** [comment]
This is in production -- please take a look and close if everything looks good

**Comment by svarlamov** [comment]
CC @LanderMuruaga

**Comment by svarlamov** [comment]
Pls review/close @LanderMuruaga

**Comment by LanderMuruaga** [comment]
Looking good in production.
