### ISSUE TITLE
Show edit on GitHub button in course content

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#20]
@LanderMuruaga I think it'd be very helpful to directly link EXLskills cards (and likely course homepages) to Github. Probably via something like various "Edit on GitHub" buttons.

- [x] Track course repo URL in course yaml

- [ ] Add edit URL to card and course records in mongo

- [x] Get designs for this feature

- [ ] Expose fields via GQL API

- [ ] Implement in course cards GUI

- [ ] Implement in course home/info GUI

**Comment by LanderMuruaga** [comment]
Edit in Github on **Course Question**
Different options...
1. Regular, simple, Edit in Github link with icon
2. Dropdown showing available options in case we need to display more functionalities, i.e. Show as Cards

------

**1. Regular, simple, Edit in Github link with icon**
![editgit-simple](https://user-images.githubusercontent.com/41282864/47097904-9c765a80-d232-11e8-9a6a-8015a7001c32.png)

------

**2. Dropdown showing available options in case we need to display more functionalities, i.e. Show as Cards**
![editgit-more](https://user-images.githubusercontent.com/41282864/47097953-af892a80-d232-11e8-99e7-3ef0c193a816.png)

**Comment by svarlamov** [comment]
@stanvarlamov In eocsutil, I added `github_edit_url` field to each `card` document (the same document that contains the new `course_item_ref`). Can you add this field to GQL so that the client can get it for cards to then display in the UI? Let me know when that's being sent over -- thanks

**Comment by stanvarlamov** [comment]
Coded and pushed
