### ISSUE TITLE
Incorrect Code Output

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#27]
**URL:** https://exlskills.com/learn-en/courses/ap-computer-science-a-java-ap_java/content

**Current behavior:** The run results have an additional line of code below them.

**How to Recreate:** Click on "Run" on the example for reserved words.

**What to Fix:** Results of run program.

**Expected Outcome:** 
![image](https://user-images.githubusercontent.com/33239272/44123940-9dde025e-9ff8-11e8-886c-acadfc88d578.png)+

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44123634-41d3ce04-9ff7-11e8-9e4b-42817fe3a420.png)

**Comment by svarlamov** [comment]
@kkhenkina-EXL it's a bash **terminal** so that's how it works. We'll get started on an intro course/video that explain these things to users

**Comment by svarlamov** [comment]
What's more interesting is that you only noticed this for one example? Btw the terminal isn't up right now - I'm updating some stuff there right now

**Comment by kkhenkina-EXL** [comment]
@svarlamov at first it really didn't phase me because I've seen it in my linux classes but also wasn't sure if that would be expected in this case.

Quick q - am I correct in assuming users should be able to edit the terminals and run their code?

**Comment by svarlamov** [comment]
Yeah that's the goal. Same for sysadmin courses, etc

**Comment by svarlamov** [comment]
Closing as this is not really relevant -- at least as an issue in this form... Separately there are some bash messages (regarding the kernel warnings) that I am cleaning up, but that's another story...
