### ISSUE TITLE
Spacing between questions and answers

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#28]
**URL:** https://exlskills.com/learn-en/courses/ap-computer-science-a-java-ap_java/units/java-syntax-and-style-e68ae5890cc143a88fb940e3a0716db4/sections/basic-syntax-560ab490eff141daadc1f48ce626eed7/card/print-output-c7b8c4efb69c42219f2860f3558f6135

**Current behavior:** Large space between question and answer options.

**How to Recreate:** Navigate to a question that has long answers that require scrolling.

**What to Fix:** Space between question an answer options.

**Expected Outcome:** 
![image](https://user-images.githubusercontent.com/33239272/44124341-c63f5264-9ffa-11e8-9081-cbed4a38e5a6.png)

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44124231-190ecd90-9ffa-11e8-8e78-ca597fa1bb31.png)

**Comment by LanderMuruaga** [comment]
Working on it. Even they are fully functional, this pages need some love.

**Comment by svarlamov** [comment]
@LanderMuruaga This is because of the behavior of the split toggle... I think that it's an area of focus on this page... Not urgent though -- obviously this stuff is functional, so it's just improvements

**Comment by svarlamov** [comment]
I'm not sure that this issue itself is going anywhere... @LanderMuruaga I suggest to close unless we can come up with something actionable here

**Comment by LanderMuruaga** [comment]
Agree, I think is good to track them so we can come back to it later, but in general we'll face all aesthetic/alignment issues in na near future (TBD).
