### ISSUE TITLE
"Show Hint" After Submission Blocks "Next" Button

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#29]
**URL:** https://exlskills.com/learn-en/courses/ap-computer-science-a-java-ap_java/units/java-syntax-and-style-e68ae5890cc143a88fb940e3a0716db4/sections/basic-syntax-560ab490eff141daadc1f48ce626eed7/card/indentation-7517e2ea7d634feb9a29ed89381103c9

**Current behavior:** If the "Show Hint" button is pressed after an answer is submitted the "Next question" or "Try Again" dialogues disappear.

**How to Recreate:** Submit an answer, click on "Show Hint".

**What to Fix:** Availability of pop-up "Try Again" or "Next Question" buttons.

**Expected Outcome:** The popup should remain available even if the "Hint" button is clicked first.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44125361-1d582aa8-a000-11e8-857d-07a336571e1f.png)

**Comment by LanderMuruaga** [comment]
Interesting point. 
Need to check the whole interaction model for this piece/buttons. 
Again, is fully functional, but we can do it much better :)

We need to look at it strategically to understand the effort required to redesign/change this part and decide what to do with it.

**Comment by svarlamov** [comment]
I fixed this a while ago...
