### ISSUE TITLE
Course Section Navigation in Learn Mode

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#30]
**URL:** https://exlskills.com/learn-en/courses/ap-computer-science-a-java-ap_java/units/java-syntax-and-style-e68ae5890cc143a88fb940e3a0716db4/sections/errors-c7a7684d93214991a5c866e8d7c77cd1/card/runtime-errors-b17ff28d5c204c259d4ed8499472c228

**Current behavior:** You cannot switch between class sections using the navigation at the top of the page.

**How to Recreate:** Go to the learn mode of any section and try to click the "<" and ">" to switch to previous or future sections.

**What to Fix:** Click ability of the section navigators.

**Expected Outcome:** Should be able to move forward and backward in the course using the navigation buttons.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44125561-5d3d8ff4-a001-11e8-9a68-9e3cdbb9c8eb.png)

**Comment by svarlamov** [comment]
So I spent some time with this in the code... It's really a mess and the library that's used is garbage. @landermuruaga this is something that I suggest we redesign as it's confusing and doesn't fit well on mobile either

**Comment by LanderMuruaga** [comment]
Solved with new navigation and functionalities. 
![exlkit-course doing_](https://user-images.githubusercontent.com/41282864/46944120-8b322000-d071-11e8-8cf9-11da91b8fa3a.png)
