### ISSUE TITLE
Marketing website footer discrepencies 

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#31]
**URL:** https://exlskills.com/en/pricing/

**Current behavior:** Text on the main site sounds a bit off.

**Expected Outcome:** 
![image](https://user-images.githubusercontent.com/33239272/44125935-3de7b740-a003-11e8-817d-e61ce9be7c5e.png)

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44125837-c5b42be6-a002-11e8-933c-b6086b3d9e11.png)

**Comment by svarlamov** [comment]
Yeah that is off. Only happening on pricing page?

**Comment by kkhenkina-EXL** [comment]
That's the only place I've found the description so far. Is there a quick way to get a list of all pages under the domain to confirm?

**Comment by kkhenkina-EXL** [comment]
This is also used here: https://exlskills.com/zh/%E4%BB%98%E8%B4%B9%E6%96%B9%E6%A1%88/
Which is in atrocious shape and should NOT be published IMO.
![image](https://user-images.githubusercontent.com/33239272/44130968-fc79e0d8-a01d-11e8-8691-1fb85110988c.png)


And is Footer 4 in WP. Would you like me to make the changes as I proposed above? Or would you like me to tinker with it some more?

**Comment by svarlamov** [comment]
Just delete the chinese version of that page... I can't believe that it was ever published @EXLSunny

**Comment by svarlamov** [comment]
Can we close this now @kkhenkina-EXL ?

**Comment by kkhenkina-EXL** [comment]
@svarlamov do you want me to make the proposed changes to the footer?

**Comment by svarlamov** [comment]
Ummm no... I think that the footer should be the same as on the index page and delete the chinese version of the pricing page (if it still even exists) since it does not have the latest code

**Comment by svarlamov** [comment]
Just in case -- to clarify:

![image](https://user-images.githubusercontent.com/10859025/44319703-0ca17380-a470-11e8-9a71-0c4e652aaf09.png)

**Comment by kkhenkina-EXL** [comment]
The footer has been changed accordingly and the Chinese version of the page has been deleted.
