### ISSUE TITLE
Highlighted Links in Header

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#32]
**URL:** https://exlskills.com/en/*

**Current behavior:** The highlight color of the links is different on the header if it's scrolling or at the top of the page.

**How to Recreate:** Scroll down the page and watch the selected item on the header change color.

**What to Fix:** Color of highlighted link in header.

**Expected Outcome:** Highlighted links should highlight the same color regardless of scroll.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44131039-5ff75956-a01e-11e8-97cf-0c885009dc95.png)

**Comment by svarlamov** [comment]
Umm the button style changes intentionally... Not sure abt the colors

**Comment by svarlamov** [comment]
Please un-assign me as I'm not really relevant on these issues.. CC @LanderMuruaga

**Comment by svarlamov** [comment]
@kkhenkina-EXL You are all setup with WP, so I suggest if you feel that this is something worth tackling (i'm not sure...) you can implement there or close this

**Comment by kkhenkina-EXL** [comment]
Highlighted text color has been adjusted, closing this out now!
