### ISSUE TITLE
Display "Outage" message when backend services are down

### ISSUE THREAD

**Issue by stanvarlamov** [exlskills/exlskills#36]
Currently, if, e.g., the GQL server is down, the client is not operational but doesn't reflect the lost of functionality. Instead, unstructured software-produced errors show in individual fields on the screen. Need a method of replacing the client with an outage message

**Comment by svarlamov** [comment]
@LanderMuruaga Can you design an overlay for this state? This will happen if one of the critical backend services is not accessible by the client... So something to the effect of, 'Check your internet connection or reload in a few seconds' message

**Comment by LanderMuruaga** [comment]
Text could be customized, and automatic reload deleted.
![slow-reload](https://user-images.githubusercontent.com/41282864/44519333-052ad600-a6cd-11e8-9a56-daa5d6f4aad2.png)

**Comment by svarlamov** [comment]
Issue deprecated by move to spf-server
