### ISSUE TITLE
"Upgrade" Button MIA on Mobile

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#40]
**URL:** exlskills.com/learn-en

**Current behavior:** If you are logged into an account on mobile you cannot see the "Upgrade" button and there is no other way to access the link.

**How to Recreate:** Log into an account w/o an active subscription using a mobile device.

**What to Fix:** Availability of "Upgrade" button on mobile layout.

**Expected Outcome:** Ability to upgrade service even through a mobile device interface.

**Current State Screenshot:** 
![image-1](https://user-images.githubusercontent.com/33239272/44482506-896e5200-a616-11e8-98ef-af193ff94e7d.jpg)

**Comment by svarlamov** [comment]
Well you can see why -- there is no room for it... CC @LanderMuruaga

**Comment by kkhenkina-EXL** [comment]
This is true! But you should still be able to get a link through the "Billing" section of the settings page? Or some other creative solution per Lander.

**Comment by LanderMuruaga** [comment]
Both are right. 
No room for it of course, but it also needs to be displayed somewhere else. 
I think the best place is inside the menu. This is where is expected to be or where I expect to find it. I mean, when the mobile menu appears it brings all elements on the header that have no room on the mobile layout. That way it is accesible from every page or section.

**Comment by svarlamov** [comment]
This is no longer relevant since we are now using credits and they show on both mobile and desktop.
