### ISSUE TITLE
Typo in Subscription Confirmation

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#41]
**URL:** https://billing.exlinc.com/hostedpage/2-11b415830677904a909bf155735b64d2e6ea8a8d94a40a758c00eeab4b579fee8f240dcb304500a278a71458cacf5f92/thankyou

**Current behavior:** The Product Name as it appears on the payment confirmation page is missing spaces.

**How to Recreate:** Subscribe for the first time to EXLskills.

**What to Fix:** Product name grammar

**Expected Outcome:** "EXLskills - EXLskills" not EXLskills-EXLskills

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44482567-bd497780-a616-11e8-989d-6b7a08311ab9.png)

**Comment by svarlamov** [comment]
We're re-doing the billing flow, so this is no longer an issue
