### ISSUE TITLE
EXLskills Logout

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#42]
**URL:** https://exlskills.com/en/

**Current behavior:** When you "Log Out" of EXLskills you're sent to the exlskills.com marketing site.

**How to Recreate:** Log out of an account on EXLskills.

**What to Fix:** Page which users are redirected to upon logout.

**Expected Outcome:** You should be redirected to the login page.

**Comment by svarlamov** [comment]
Why is that you think? Since you don't have to be logged in to use the system, I don't see a solid rationale for that. I would rather showcase the marketing site. CC @LanderMuruaga

**Comment by kkhenkina-EXL** [comment]
My logic is that (per my amendment to the Password issue #43 - users should be logged out due to inactivity.) should users logged out always be redirect them to the marketing page? I'd rather see a login screen and be able to get right back to where I left off if I'm timed out.

Also - If users are actually logging out (not just closing browser) it's usually to switch accounts or stop working on whatever it is so someone else can access the machine, These users would probably be logging back in before wanting to review the marketing site IMO.

**Comment by LanderMuruaga** [comment]
Usually the logout is voluntary, I mean is not an error or done by mistake.
Taking into account that in our system you do not need to login, we can keep the user in the same place(to keep that "no need to login consistency"), but letting them know they are logged out. This could be through a notification.

As soon as the user knows what is going on, is ok.

**Comment by svarlamov** [comment]
Gotta chime in here as well... There is a much stricter inactivity timeout for for sensitive areas of the site (like the account management page), however, I think it is just terribly annoying to be logging users out on the normal page. Even GitHub (a site where people manage lots of private info) doesn't really have an inactivity timeout... Can we close or re-open this with a clearer goal? I'm not really following what the point of this issue is

**Comment by kkhenkina-EXL** [comment]
If you're both fine with the redirect as is that's fine with me!

**Comment by stanvarlamov** [comment]
As a logged in user has access to credit management, purchasing, etc., as a security measure, an explicit click on "Log Out" should clear the user session and cookies so that no one can (accidentally) get into the user's account by simply accessing the site again on the same browser

**Comment by svarlamov** [comment]
That's already how it works. Just click on your profile and logout. Done
