### ISSUE TITLE
Password Requirements

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#43]
**URL:** https://accounts.exlinc.com/auth/realms/exlinc/protocol/openid-connect/auth?response_type=code&redirect_uri=https%3A%2F%2Fauth-api.exlskills.com%2Fauth%2Fkeycloak%2Fcallback&client_id=exlskills

**Current behavior:** You can use any length password with any characters in it.

**How to Recreate:** Select "Register" to set up a new account, or go to account settings to edit a current password.

**What to Fix:** Password requirements.

**Expected Outcome:** Passwords need to have the following requirements for security purposes:
- 8 char minimum
- 1 specialty char
- 1 number
- 1 capital letter

**Comment by svarlamov** [comment]
Relatively straightforward to set this up via Keycloak... Will look into it

**Comment by kkhenkina-EXL** [comment]
@svarlamov forgot to mention - this should also be enforced at user password changes, as well as not being able to use the 4 most recent passwords. PW changes should probably be required every 90 days.

**Comment by kkhenkina-EXL** [comment]
@svarlamov one more thing - do we have an inactivity timeout? If not, should limit it to like 15-20 min.

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
