### ISSUE TITLE
Logged Out Lag

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#44]
**URL:** exlskills.com/learn-en

**Current behavior:** If you log out and navigate back to exlskills.com/learn-en the page is blank until it is refreshed a few times.

**How to Recreate:** Log out of your EXLskills account, click on "Get Started" on the homepage once you're redirected there.

**What to Fix:** Blank screen/need to refresh.

**Expected Outcome:** I should just see /learn-en.

**Comment by svarlamov** [comment]
@kkhenkina-EXL Can you try this out again? I'm unable to replicate that behaviour. I do briefly see a graphql-related error in the header when I click log out, but once I click the "try it out" button on the landing page everything loads fine for me.

**Comment by kkhenkina-EXL** [comment]
@svarlamov  Unfortunately still experiencing this, video: https://exlinc-docs.awsapps.com/workdocs/index.html#/share/document/f55a7b3506147611015579a5d0d59e4cab486185cc715e61034c6583bca5ea17 not sure if I just click too fast?

**Comment by svarlamov** [comment]
Thanks for the video, next time please also show console output (with preserve log enabled) but this time it was okay as I can replicate. Doesn't seem to be related to the speed of the process, just to the steps themselves. Client issue. Will fix

**Comment by svarlamov** [comment]
@kkhenkina-EXL I believe that the latest production has a fix for this... Can you check it out?

**Comment by kkhenkina-EXL** [comment]
LGTM
