### ISSUE TITLE
e-Mail Change Issues

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#45]
**URL:** https://www.exlskills.com/learn

**Current behavior:** If you change your email in the "Account Settings" links you will not be able to correctly access your avatar or zoho services.

**How to Recreate:** Change the email related to an account with a subscription and try to access the Billing console. Or look at the avatar.

**What to Fix:** Updates to all related systems once an e-mail address is changed by a user.

**Expected Outcome:** If an email address is updated all systems should be updated with that email address as well.

**Comment by svarlamov** [comment]
Deprecated and removed Zoho, so this is no longer relevant
