### ISSUE TITLE
Question Grading Trigger in Exams

### ISSUE THREAD

**Issue by stanvarlamov** [exlskills/exlskills#46]
Currently, question grading in exam is triggered by a change in the answer section, including grading requests for WSCQ questions being triggered by changes inside the Editor. This causes unnecessary and uncontrolled traffic to the grading engine. The suggested trigger should be on "leaving" the question page via navigation buttons / slider. The grading should be called if changes were made to the question's answer / code

**Comment by svarlamov** [comment]
Done
