### ISSUE TITLE
Header Misalignment on Pages w/ Side-Nav

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#47]
**URL:** https://exlskills.com/learn-en/settings & https://exlskills.com/learn-en/courses

**Current behavior:** The header options are still in the middle of the screen as they are on the dashboard page.

**How to Recreate:** Open either courses or settings and see the header options still in the middle.

**What to Fix:** Header on pages that have side-nav.

**Expected Outcome:** The left-aligned items on the header should be on the left, right should go right. 

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/44538044-3fe13e00-a6ce-11e8-8189-f25f328d38a6.png)

**Comment by svarlamov** [comment]
Will be fixed by updated layout. Closing
