### ISSUE TITLE
Duplication of Download Option

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#48]
**URL:** https://billing.exlinc.com/portal/exlinc/index#/invoices/invoice/1361845000000151089

**Current behavior:** There is a "Download" button as well as a "Download PDF option in the drop-down menu.

**How to Recreate:** Look at an invoice and click on the drop down to show additional options.

**What to Fix:** Duplication of download option/ "extra options" drop down/print option.

**Expected Outcome:** We should just have a download button, maybe with icon and "Download" text, and remove the drop down list and have a print icon.

**Current State Screenshot:** ![image](https://user-images.githubusercontent.com/33239272/44548319-b93b5980-a6eb-11e8-9605-7ca17bb5379e.png)

**Comment by svarlamov** [comment]
This is Zoho. Call support. Can't fix

**Comment by svarlamov** [comment]
Also I'm pretty sure they do this bc not all ppl would recognize the icon... Anyways if u want to call them u can, but I'm going to close this because it's pretty off topic right now
