### ISSUE TITLE
Finalize REPL problem display and grading

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#5]
- [x] Correct data sent to client for code problem rendering

- [x] Fix REPL (code problem) display

- [x] On submit, get solution from REPL via iframe postmessage

- [x] Implement grading API on the GQL server to score the problem

- [x] Implement grading backend

**Comment by svarlamov** [comment]
Updates to the WSCQ question `data` field:

Fields to drop:
* `code`
* `code_tags`
* `validation_code`

New/changed fields:
* `api_version` - plain string 
* `src_files` - intl string workspace files that represent the solution
* `test_files` - plain string workspace files that are used to test the solution
* `tmpl_files` - intl string workspace files that are used client-side as a template for the user (potentially with instructions in comments)
* `grading_strategy` - plain string with a key for the testing strategy (just `default` for now always)
* `grading_tests` - plain string with an object (each key corresponds to a grading test) of commands that are used for grading (individual tests)

**Comment by stanvarlamov** [comment]
Use WSENV signalling API to get the URL to a wsenv instance: https://wsenv-signalling-api.exlcode.com/v0/connect
It's the URL to the WSENV websocket endpoint -> the hostname for HTTPS instead of WSS
Future: this endpoint will also be generating a JWT needed in order to connect to the WSENV instance

**Comment by svarlamov** [comment]
In production, functional for Java. Other langs might require more work here and there, but closing this issue as the primary impl is complete
