### ISSUE TITLE
Decrease initial page load time

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#55]
Right now it takes several seconds to initially load most pages in the app -- this is largely due to the weight of the frontend... This causes a lot of user attrition and we need to speed it up to capture a higher percentage of users that discover EXLskills

**Comment by svarlamov** [comment]
Reconfigured gzip to correctly serve static files with compression. Reduced size of main JS chunk by 75% (less than 500kb now)

**Comment by stanvarlamov** [comment]
Identified Translations and Localization content as an opportunity to remove (except the required one)  from the initial bundle - see #56

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
