### ISSUE TITLE
Optimize Load of Locale-specific Translations

### ISSUE THREAD

**Issue by stanvarlamov** [exlskills/exlskills#56]
Currently, all translations are physically assembled into the main js chunk, which includes json files and `moment` - provided locales. 
https://github.com/moment/moment/issues/4025 has multiple points listed on how their part can be optimized. Need to review and see what can be implemented and how. The implementation should work using the existing version of webpack (2)

**Comment by stanvarlamov** [comment]
The translation content included into the main js chunk from `/app/translations/...json` files and from the `moment` package is total about 350Kb, which is 15% of the current 2Mb main chunk. Leaving most of it out may help speeding up the compilation of the initial chunk

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
