### ISSUE TITLE
web-client PlainLink causes browser Warning on enclosed links (<a>) in SideBarMenu

### ISSUE THREAD

**Issue by stanvarlamov** [exlskills/exlskills#57]
Before app/common/components/PlainLink/index.tsx was introduced on Aug 20 and added above ItemWrapper in SideBarMenu (https://github.com/exlskills/web-client/commit/bee8be02a6e9e1983e3fb4992c38d3e6a4ea26b2), the SideBarMenu item was being generated as HTML `<t>` and the child component with the Text provided `<a>` link functionality. 

After the change, the PlainLink is the source of the `<a>` element in the HTML. However, the child component remains as an `<a>` as well. This causes a warning in the browser that `<a>` cannot be a descendant of `<a>`. Although, this doesn't seem to affect the functionality in either Chrome or Firefox, suggest reviewing if one of the components can be corrected. 

See the page details in React Tool:

![before plainlink](https://user-images.githubusercontent.com/21002807/45154553-7ceb1b80-b20a-11e8-8ff8-6615b4638b42.png)
![with plainlink](https://user-images.githubusercontent.com/21002807/45154582-9c824400-b20a-11e8-81a7-5f21575d8164.png)

**Comment by svarlamov** [comment]
Noticed these warnings as well but didn't have a chance to track down the line # in the TS. Do you have that on-hand already?

**Comment by stanvarlamov** [comment]
Fixed by adding an identical styled component for the Item enclosed into the PlainLink, with `div` vs. `a`. Pushed with the `code-splitting-work` enhancements

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
