### ISSUE TITLE
Course card UI, dashboard UI, courses list UI update

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#61]
Updating the design for the 'card' that shows up on /courses and in various course carousels

### Desktop

![01-dashboard](https://user-images.githubusercontent.com/41282864/45565141-fa3e0e00-b852-11e8-99ab-60ad613bdfac.png)

![02-courses](https://user-images.githubusercontent.com/41282864/45565202-2d809d00-b853-11e8-892a-edef20aadebb.png)

Note the right menu brings some extra elements to figure out if the fit there or not. 
This could be a future feature.

### Mobile

![m-01-dashboard](https://user-images.githubusercontent.com/41282864/45565250-57d25a80-b853-11e8-8251-143ec7cb281b.png)

![m-02-courses](https://user-images.githubusercontent.com/41282864/45565266-67ea3a00-b853-11e8-9cb6-ede337ac2367.png)

- [ ] Update in card component

- [ ] Update usage in carousels

- [ ] Update dashboard

- [ ] Update courses list

**Comment by LanderMuruaga** [comment]
Updated designs

**Comment by svarlamov** [comment]
@LanderMuruaga Can you please clarify the logic for resizing the course cards? For instance, how do we manage the image dimensions, etc.

Also would be nice to have the dimensions for the card and what the padding is btwn components

**Comment by svarlamov** [comment]
@LanderMuruaga Also if you were checking things off -- pls don't. Unless it starts with "Design ..." because they will be checked off as they are actually implemented

**Comment by LanderMuruaga** [comment]
@svarlamov updated Dashboard and Course grid in both Desktop + Mobile with the right size of cards.
All they bring the same size, but I think next info is interesting for card behaviour (1).

**IMAGE usage**
I like this way of using images...
https://getbootstrap.com/docs/4.1/content/images/
(1) Behaviour should be like this... https://getbootstrap.com/docs/4.1/examples/album/#

I'm preparing a doc with all **marging/paddings**.

**Comment by LanderMuruaga** [comment]
> @LanderMuruaga Also if you were checking things off -- pls don't. Unless it starts with "Design ..." because they will be checked off as they are actually implemented

Not touching nothing is not assigned to me or related to design. Anyway if it was me, I'm so sorry.

**Comment by LanderMuruaga** [comment]
@andyluu1908 adding Dashboard + Course list Dark theme 

![d-01-dashboard](https://user-images.githubusercontent.com/41282864/45695118-0b439380-bb61-11e8-9536-5a99cef6adb1.png)
![d-02-courses dark](https://user-images.githubusercontent.com/41282864/45695119-0b439380-bb61-11e8-9c38-065b7b03f644.png)

**Please**, note that the left sidebar content is a "future projection". Right now we don't have all this contents, but is good to have it in mind for a near future.

**Comment by LanderMuruaga** [comment]
IMPORTANT: 
Discussion and updates to this issue have been moved to Issue https://github.com/exlskills/exlskills/issues/74

**Comment by LanderMuruaga** [comment]
**IMPORTANT:** 
Discussion and updates to this issue have been moved to Issue https://github.com/exlskills/exlskills/issues/74
