### ISSUE TITLE
Setup backend devstack for improved first-time dev experience

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#67]
Interview project 1 for @andyluu1908 

- [ ] Setup a `docker-compose.yml` in the new repo at https://github.com/exlskills/devstack that should be comprised of the MongoDB v3.6, `gql-server`, `auth-server`, and `usi-server`

- [ ] Create LICENSE file for Apache v2 license for the devstack project

- [ ] Create a README.md file that explains what the devstack project does, the pre-reqs, how to install it, how to run it, how to customize it, and how to contribute back to it

- [ ] Setup keycloak default realm automatically via a JSON file (ideally). If not realistic to do so, then add detailed instructions for setup

- [ ] Setup a default data import for the mongodb data

**Comment by svarlamov** [comment]
@stanvarlamov When you have a chance can you follow up on this issue? And then we can update the docs for the `exlskills/devstack`. Will be a great feature to have rounded out for all new devs

**Comment by stanvarlamov** [comment]
A complete and working docker-compose devstack has been set up and tested. Some additional features may need to be added, e.g., time-based data seeds. Thorough documentation is a WIP, but the tasks per the initial check list have been completed, so closing the issue
