### ISSUE TITLE
General styling

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#68]
Style and specs discussion.
Will cover from brand styles to interface layout and spacings, fonts, colors, etc.

Aligned with the new styles, here are some specs...

1. General styles (interface)
 - Typography
 - Colors
2. Mobile layout specs
  - General rules 
  - Layout spacing
  - Top menu (dropdown) spacing
  - Content modules spacing

**Download Specs document**

[EXLskills-Specs-v01.pdf](https://github.com/exlskills/exlskills/files/2388661/EXLskills-Specs-v01.pdf)

[EXLskills-Specs-v02.pdf](https://github.com/exlskills/exlskills/files/2391940/EXLskills-Specs-v02.pdf)

**Comment by LanderMuruaga** [comment]
Adding styles for cards + container

-----------
Example: https://getbootstrap.com/docs/4.1/examples/album/
-----------

**COTAINER LAYOUT**

.container {
	width: 100%
	}

* Breakpoints + Content width relationship

@media (min-width: 1200px)
.container {
	max-width: 1140px;
	}

@media (min-width: 992px)
.container {
	max-width: 960px;
	}

@media (min-width: 768px)
.container {
	max-width: 720px;
	}

@media (min-width: 576px)
.container {
	max-width: 540px;
	}

—————


**COLUMN LAYOUT**

2 columns for small screens (less than 768px)
3 columns for wide screens (over 768px)

We can change it to 4 cols if necessary. This method helps us to change it easily.

From— @media (min-width: 1200px) — to—  @media (min-width: 992px)
.col-md-4 { 	max-width: 33.333333%;
	}

From — @media (min-width: 768px) — to — @media (min-width: 576px)
.col-md-4 { 	max-width: 50%;
	}

**Comment by svarlamov** [comment]
@andyluu1908 I'm sure that you already got the notifications, but please make sure to check out my comments on your last PR prior to working on this. Also make sure to grab a fresh copy of the `master` branch of `web-client` as it has lots of new changes

**Comment by LanderMuruaga** [comment]
@andyluu1908 here is a small doc with colors in place.
Hope is helpful.

![color-specs-light-theme](https://user-images.githubusercontent.com/41282864/45674927-6019e680-bb2e-11e8-96c2-a008e9a3b0e8.png)

**Comment by LanderMuruaga** [comment]
Dark theme colors.
I'm updating the PDF on the top with some minimum fixes.
![color-specs-dark-theme](https://user-images.githubusercontent.com/41282864/45676038-20083300-bb31-11e8-9c57-3a7fc2051248.png)

**Comment by LanderMuruaga** [comment]
Adding Desktop layout with sidebar + header spacing.

![desktop-layout-w_sidebar](https://user-images.githubusercontent.com/41282864/45687563-75ebd380-bb4f-11e8-81a0-45be2efaecc6.png)

**Comment by LanderMuruaga** [comment]
Adding specs for desk layout and container... 
@andyluu1908, suggestions are welcome if you want to discuss any kind of spec/sizing/matter

![desktop-layout-specs](https://user-images.githubusercontent.com/41282864/45813986-6cd83f00-bcd4-11e8-936f-126c1c906e81.png)

**Comment by LanderMuruaga** [comment]
Internal modules spacing... 
1 col, 2 cols, 3 cols.

![desktop-layout-specs2](https://user-images.githubusercontent.com/41282864/45832997-c0ae4c80-bd03-11e8-9577-6bcae485a838.png)

**Comment by LanderMuruaga** [comment]
Updated
![color-specs-dark-theme](https://user-images.githubusercontent.com/41282864/45941001-8501d400-bfdc-11e8-8040-6bbdf83a37e3.png)

**Comment by LanderMuruaga** [comment]
Sidebar behavior... 
![sidebar behaviour](https://user-images.githubusercontent.com/41282864/45943898-80dbb380-bfe8-11e8-9419-aa2d7fe2a648.png)

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
