### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#70]
@svarlamov @andyluu1908 some screens that represent the flow for billing...

Flow/Screen order:
1. Button on top (Credits w/ star)
2. Login (if not loged)
3. Add credit card
4. View card or remove it

DESKTOP

![desk - billing 00](https://user-images.githubusercontent.com/41282864/45759320-f4b43f80-bc27-11e8-8c06-4f5214e3e650.png)
![desk - billing 01](https://user-images.githubusercontent.com/41282864/45759323-f67e0300-bc27-11e8-9ef8-c7573a108c07.png)
![desk - billing 02](https://user-images.githubusercontent.com/41282864/45759328-f847c680-bc27-11e8-8e01-019d28c25102.png)
![desk - billing 03](https://user-images.githubusercontent.com/41282864/45759331-f978f380-bc27-11e8-9af3-44fd852a0967.png)
![desk - billing 04](https://user-images.githubusercontent.com/41282864/45760665-e7e51b00-bc2a-11e8-9c87-552579488446.png)
NOTE: This last screen is for confirmation. When user click Buy, he gets a confirmation. Once they click "Purchase more", the form appears again. 
**(!) Important:** If In case it is not possible to switch between the "Buy credits little form" and the "Confirmation message", we can just push it down to show the confirmation above it (+ delete the buy more button that makes not sense in this case).

MOBILE

![mobile - billing 00](https://user-images.githubusercontent.com/41282864/45759346-05fd4c00-bc28-11e8-81ae-7a8fc2100c54.png)
![mobile - billing 01](https://user-images.githubusercontent.com/41282864/45759349-07c70f80-bc28-11e8-9562-0ec31d51db9c.png)
![mobile - billing 02](https://user-images.githubusercontent.com/41282864/45759354-0a296980-bc28-11e8-89b5-4cb3c9492389.png)
![mobile - billing 03](https://user-images.githubusercontent.com/41282864/45759358-0b5a9680-bc28-11e8-80a1-e14b529bed4a.png)

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
