### ISSUE TITLE
Cards, banners & responsive elements

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#71]
Information about course cards, banners and responsive elements...

CARDS:
All they bring the same size, but I think next info is interesting for card behaviour (1).

**IMAGE usage**
I like this way of using images...
https://getbootstrap.com/docs/4.1/content/images/
(1) Behaviour should be like this... https://getbootstrap.com/docs/4.1/examples/album/#

I'm preparing a doc with all **marging/paddings**.

_Originally posted by @LanderMuruaga in https://github.com/exlskills/exlskills/issues/61#issuecomment-421429375_

**Comment by LanderMuruaga** [comment]
Responsive behaviour

![sidebar behaviour](https://user-images.githubusercontent.com/41282864/46549270-b11d2f00-c8d1-11e8-85ea-80fa9da09196.png)
![sidebar behaviour2](https://user-images.githubusercontent.com/41282864/46549271-b11d2f00-c8d1-11e8-9429-f6571ce663e2.png)

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
