### ISSUE TITLE
CC Entry Text Color

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#73]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** The credit card number entry text is difficult to read due to it being black.

**How to Recreate:** Open the billing console and attempt credit card number entry.

**What to Fix:** Text color of credit card entry.

**Expected Outcome:** These fields should have of background color per the designs in #70.

**Current Screenshot:**
![image](https://user-images.githubusercontent.com/33239272/46327391-68166380-c5cf-11e8-8f3e-cf65099282bc.png)

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
