### ISSUE TITLE
[GQL] New exam/quiz queries/mutations

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#79]
Tasks:

- [x] Add field to `question` schema `exam_only: boolean (optional, default false)`

- [x] `mutation startExam(courseID, unitID) -> ExamSession // Check that I have not exceeded limits`

- [x] `mutation setExamQuestionAnswer(examSessionID, questionID, question data) -> void // Don't return correct of false, just record input and return OK`

- [x] `query getCurrentExamQuestionAnswer(examSessionID, questionID) -> question data | null`

- [x] `mutation submitExam(examSessionID) -> ExamSession // Check that the time limit hasn't expired. Return with score data, etc. on success`

- [x] Setup cron/task to run every few seconds to check all exams and if not submitted and over time, then grade and record score (probably also add a field overtime_submit=true)

- [x] For card questions, we're pretty set, however, for `mutation SubmitCardAnswerMutation` check that the question being submitted is not an exam question (`question.exam_only=false`) so that people can't scrape exam questions like that. Same for the Question Hint.

- [x] Add a `has_exam` field to each Unit response that should be calculated by checking to see if an exam with that unit ID exists. This will let the client know if it should show a 'Take Exam' button for that unit and on the progress page whether to show a score

- [x] Add `{key:value}` schema for doc refs (replacing the arrays structure). Write basic conversion for existing transaction docs 

- [x] Ensure USI is validated / updated to work with the new structures

- [x] Implemented updated schemas in eocsutil import

**Comment by svarlamov** [comment]
All done from the eocsutil side of things

**Comment by stanvarlamov** [comment]
Will be closing soon once the latest server code with `card_ref` removed is pushed into USI and GQL

**Comment by stanvarlamov** [comment]
Continues in #87 and #86 as further enhancements
