### ISSUE TITLE
Check-answer button not clickable after submitting empty answer.

### ISSUE THREAD

**Issue by EXLSunny** [exlskills/exlskills#8]
In `Practice`(the quiz), after I click Check-answer Button without choosing any options, the red message showed up 

> please answer the question

<img width="1071" alt="screen shot 2018-08-09 at 18 32 53" src="https://user-images.githubusercontent.com/40050824/43893915-24c4ca40-9c03-11e8-9b3b-e1bbd11c0cfd.png">

Meanwhile, the Check-answer button turned grey and not clickable anymore. Even after I did choose a new answer, the Check-answer was still unclickable. 

<img width="1064" alt="screen shot 2018-08-09 at 18 33 32" src="https://user-images.githubusercontent.com/40050824/43894072-9acc7576-9c03-11e8-9d47-b7b465e2a48b.png">

The desired situation should be like when I choose a new answer, the Check-answer button needs to be clickable. 

<img width="1068" alt="screen shot 2018-08-09 at 18 33 13" src="https://user-images.githubusercontent.com/40050824/43894086-a1d1cc04-9c03-11e8-9b18-f5002bccaa0a.png">

**Comment by svarlamov** [comment]
Fixed, deploying soon... Also fixed incorrect text color of no more questions header when in dark mode
