### ISSUE TITLE
Public web (marketing side)

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#83]
Adjusted to Dashkit theme.
For the header we should use the Default Dashboard theme header (dark blue) or any other that allows us to add the top banner.

Please, check both options, with and without courses:

![exlskills-index](https://user-images.githubusercontent.com/41282864/47426993-4e5fda80-d78f-11e8-813b-17b1c149857e.png)

![exlskills-index2](https://user-images.githubusercontent.com/41282864/47430360-57ee4000-d799-11e8-934c-65906c6e2574.png)

**Comment by svarlamov** [comment]
@LanderMuruaga Please post a ZIP with the assets for the design with the suggested courses

**Comment by LanderMuruaga** [comment]
New designs for Homepage and instructors site.
Added a zip with the assets.

![index-mobile-v2](https://user-images.githubusercontent.com/41282864/47721500-8d3ed600-dc50-11e8-83d9-7d92bf5f4321.png)
![index-v2](https://user-images.githubusercontent.com/41282864/47721502-8dd76c80-dc50-11e8-9d20-4ab75eb5db31.png)
![instructor-mobile](https://user-images.githubusercontent.com/41282864/47721540-a34c9680-dc50-11e8-8138-4dd2ca771600.png)
![instructor-new](https://user-images.githubusercontent.com/41282864/47721541-a34c9680-dc50-11e8-8a39-7e814453b2ce.png)
[_Aassets.zip](https://github.com/exlskills/exlskills/files/2529796/_Aassets.zip)

**Comment by LanderMuruaga** [comment]
Footer Updated

![index-v3](https://user-images.githubusercontent.com/41282864/47756191-652b9300-dca1-11e8-81a0-d97cbf5112f6.png)
