### ISSUE TITLE
Global ID escaping fails on = when passed via WS to USI

### ISSUE THREAD

**Issue by stanvarlamov** [exlskills/exlskills#85]
Examples of WS payload viewing "Introduction to Python" -> Variables -> Strings
```
{"type":"notif","payload":{"event":"card.action","data":{"action":"view","card_id":"U2VjdGlvbkNhcmQ6cWdLU3p2TEJkeVRI","course_id":"Q291cnNlOmludHJvX3RvX3B5dGhvbg&#x3D;&#x3D;","section_id":"VW5pdFNlY3Rpb246aU93VWtjbWZnbXBV","unit_id":"Q291cnNlVW5pdDpCWEVtZ3ZwaExCQVc&#x3D;","user_id":"1IZmG69iruAl"}}}
{"type":"notif","payload":{"event":"card.action","data":{"action":"view","card_id":"U2VjdGlvbkNhcmQ6dFVja2V5RVNISWdk","course_id":"Q291cnNlOmludHJvX3RvX3B5dGhvbg&#x3D;&#x3D;","section_id":"VW5pdFNlY3Rpb246aU93VWtjbWZnbXBV","unit_id":"Q291cnNlVW5pdDpCWEVtZ3ZwaExCQVc&#x3D;","user_id":"1IZmG69iruAl"}}}
```
Looks like this is the solution suggested https://stackoverflow.com/questions/24047699/x2b-and-x3d-chars-in-base64-encoded-data

**Comment by stanvarlamov** [comment]
Once the issue is fixed, this cleanup/conversion program can be executed to update each existing Card Interaction document with correct `course_item_ref` element https://github.com/exlskills/gql-server/blob/master/src/data-load/maintenance-and-conversion/card-interaction-set-course-item-ref.js 

`card_ref` elements stay unchanged by design as those are being deprecated. The program will also skip and print a list of IDs that are no longer valid in the current courses (if any). The program does not remove any data. 
Subsequently, `getCourseById` (deprecated `courseById`) returns `last_accessed_` values for the Unit, Section and Card that can be used to navigate to the proper card when the user clicks on "Continue Learning"

**Comment by svarlamov** [comment]
HandlebarsJS was escaping the IDs -- fixed that. Sent a DM @stanvarlamov regarding the USI. Think that's causing the issue now. Rolled back to a working state for now though

**Comment by stanvarlamov** [comment]
The HandlebarsJS fix works; rolled into GQL mutation on USI deprecation
