### ISSUE TITLE
Introductory Overlay Screen

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#9]
**URL:** https://exlskills.com/learn-en/dashboard

**Current behavior:** Sage's name on the top left is very small and hard to read. There is also a lot of spacing at the top of the message, but very little at the bottom. "Write a reply" is slightly misaligned from the left.

**How to Recreate:** Navigate to https://exlskills.com/learn-en/dashboard.

**What to Fix:** Sage's name size, spacing at the bottom of the message, and the alignment of "write a reply"

**Expected Outcome:** Sage's name should be at a legible size, perhaps one size smaller than the message text? The spacing at the bottom of the message should be equal to the spacing at the top. The "Write a reply" should be left aligned to Sage's avatar.

**Current State Screenshot:** 
![image](https://user-images.githubusercontent.com/33239272/43923413-b3f7c3f2-9bef-11e8-8457-94ff5a531d31.png)

**Comment by svarlamov** [comment]
This is vendored by intercom so we can't control much about this... I made some changes (and added an image of Sage) to the dialog, but we have to stay within what intercom supports for now
