### ISSUE TITLE
SPF - FE Strings i18n

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#91]
- [x] Using the [i18n lib](https://www.npmjs.com/package/handlebars-intl) already set up in the templates, create strings files and replace string literals in `*.hbs` templates. Use a strings/messages file for the declaration of the strings in English. There might be a way to automate most of this process although naming the strings might still require some manual effort (unless use string content to indicate the name of the string).
- [x] Develop message string validator to run against the `hbs` template to ensure each `intlGet` has a corresponding message defined in the intlData files
- [x] Code template for coin singular and plural statement
- [x] Intl `title` assignments in .hbs
- [x] Intl text strings in .hbs `message:`, `text:`, `text(`, `title:`, `prefilled` and `toastr` inside scripts
- [x] code `hreflang` metadata definition for `head.hbs` and `amp.hbs`
- [x] Once the strings files are ready, we will need to upgrade the router to properly handle (where comments indicate hard-coded `en/en-US` values for locale.

**Comment by stanvarlamov** [comment]
The coding for 'en' is completed. Passing to @svarlamov for the router work
