### ISSUE TITLE
In production, don't read from FS on each request for .hbs layout files

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#92]
Subject explains -- code is here: https://github.com/exlskills/spf-server/blob/master/routes/index.ts#L349

If in production mode, save the content of the files into memory so as to avoid reading those files from FS each time. Should be able to save a few MS per request

**Comment by svarlamov** [comment]
Also, to be clear, in debug mode, read from FS on each call to make sure we can get latest .hbs layouts without restarting server in dev

**Comment by stanvarlamov** [comment]
Coded, tested and deployed into the global-nav-2 branch for roll-out with the new feature
